language: crystal
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install zlib1g-dev curl liblzo2-dev liblua5.1-0-dev -qq
install:
  # Cabinet
  - pushd /tmp
  - git clone https://github.com/alticelabs/kyoto.git
  - pushd kyoto
  - sudo make install --quiet
  - popd
  - popd
  - sudo ldconfig
script:
  - crystal deps
  - crystal spec spec
